##注册中心##
#是否调试 true/false
debug=false

#是否注册中心 true/false
isServer=false

#注册中心监听端口
listOn=1990

#注册中心TCP缓冲区大小
tcpBufferSize=256

#服务端Selector组数
serverSelectors=1
serverSelectorExecutingPeriod=10000

#响应线程池
respondPoolSize=10
respondPoolExecutingPeriod=10000

#服务端处理线程池大小
serverHandlerPoolSize=10

#注册中心允许的最大Client数量
maxClients=1000

#注册中心允许的每个IP上最大Client数量
maxClientsPerIp=50

#是否客户端 true/false
isClient=false

#注册中心节点的域名/IP:端口，多个用英文逗号分隔，如设置多个则服务会同时向多个注册中心节点注册
nodes=localhost:8000

#访问注册中心的accessKey（暂时只支持单一配置）
accessKey=PcZfxIE3IRQMQvUL

#访问注册中心的accessSecret（暂时只支持单一配置）
accessSecret=UTkTfT6NKfIxGBbywmbFGA5eTPKtmpJE

#通信层
networker=http