##服务配置##
#是否调试 true/false
[SERVICE]debug=false

#是否服务端 true/false
[SERVICE]isServer=false

#是否优先调用本地服务节点（同jvm中的），默认为true，只有设置为false才不会优先调用本地服务节点
[SERVICE]localServiceFirst=false

#服务监听IP/域名（不设置则自动获取）
[SERVICE]ip=127.0.0.1

#服务监听端口（可在多个端口监听，多个用英文逗号分隔）
[SERVICE]listOn=8001

#TCP缓冲区大小
[SERVICE]tcpBufferSize=256

#服务端Selector组数
[SERVICE]serverSelectors=1
[SERVICE]serverSelectorExecutingPeriod=1000

#响应线程池
[SERVICE]respondPoolSize=10
[SERVICE]respondPoolExecutingPeriod=1000

#服务端处理线程池大小
[SERVICE]serverHandlerPoolSize=10

#允许的最大Client数量
[SERVICE]maxClients=1000

#允许的每个IP上最大Client数量
[SERVICE]maxClientsPerIp=50

#启动哪些服务，包名或类名，可使用*作为通配符，多个用英文逗号分隔
[SERVICE]includes=

#哪些服务不启动，包名或类名，可使用*作为通配符，多个用英文逗号分隔
[SERVICE]excludes=

#客户端连接池大小
[SERVICE]clientPoolSize=10
[SERVICE]clientSelectorExecutingPeriod=1000

#通信层
[SERVICE]networker=http