#是否启用#
enabled=true

#端口#
port=8080

#MCP是否启用#
mcpEnabled=true

#根目录#
baseDir=/jframework

#应用根目录，多个以逗号分隔#
webApp=/jframework

#主机名#
host=localhost

#部署名#
deploymentName=ROOT.war

#io线程数#
#ioThreads=Math.max(Runtime.getRuntime().availableProcessors(), 10)

#worker线程数#
#workerThreads=ioThreads * 8

#是否开启gzip压缩#
gzipEnabled=false

#gzip处理优先级#
gzipPriority=100

#压缩级别，默认值 -1。 可配置 1 到 9。 1 拥有最快压缩速度，9 拥有最高压缩率#
gzipLevel=-1

#触发压缩的最小内容长度#
gzipMinLength=1024

#url是否允许特殊字符#
allowUnescapedCharactersInUrl=true

#是否开启http2#
http2enabled=false

#https配置
sslEnabled=false
#sslPort=8443
#sslKeyStoreType=PKCS12
#sslKeyStore=/usr/local/apps/cert/gugumall.cn.pfx
#sslKeyStorePassword=3zo3p940
#sslContextProtocol=TLS
#sslProtocol=TLSv1.2
#sslProtocols=SSLv3 TLSv1.2 TLSv1.3
#sslCiphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
#sslCiphers=ALL:!MD5:!DHA

#websocket配置
#endpointClasses=j.shop.im.Chatting,j.shop.express.PrintCenter